"""Lightweight structural-surface geometry shared by the ANY ecosystem."""

from .curves import Arc, ArcFrame, CurveShape, DegenerateArcError, Spline, Straight
from .exact_curves import EllipticArc, CylinderIntersectionCurve
from .quadric_curves import QuadricIntersectionCurve
from .branch_curves import BezierQuadricCurve
from .batch_intersections import (
    IntersectionBatchPolicy, IntersectionPlan, IntersectionApplication,
    plan_intersections, apply_intersections, has_current_intersection_preparation, clone_prepared_geometry,
    set_prepared_face_corners,
)
from .trimmed_charts import (
    TrimmedSurfaceChart, TrimmedSurfaceCharts, query_trimmed_surface_charts,
    validate_trimmed_surface_charts_binding, evaluate_trimmed_surface_chart,
)
from .joint_edges import JointEdge, query_joint_edge
from .prepared_face_preimages import (
    PreparedFacePreimages, AuthoredFaceDefinition, query_prepared_face_preimages,
    query_prepared_authored_face_definition,
    validate_prepared_face_preimages_binding,
)
from .prepared_model_scope import (
    PreparedModelScope, query_prepared_model_scope, validate_prepared_model_scope_binding,
)
from .authored_constraint_scope import (
    PreparedAuthoredConstraintScope, query_prepared_authored_constraint_scope,
    validate_prepared_authored_constraint_scope_binding,
)
from .prepared_vertex_preimages import (
    PreparedVertexPreimages, query_prepared_vertex_preimages,
    validate_prepared_vertex_preimages_binding,
)
from .prepared_sheet_joint_component import (
    PreparedSheetJointComponent, query_prepared_sheet_joint_component,
    validate_prepared_sheet_joint_component_binding,
    validate_prepared_sheet_joint_component_selection,
)
from .prepared_member_sheet_component import (
    PreparedMemberSheetJointComponent, query_prepared_member_sheet_joint_component,
    validate_prepared_member_sheet_joint_component_binding,
)
from .prepared_planar_member_sheet_network import (
    PreparedPlanarMemberSheetNetwork, query_prepared_planar_member_sheet_network,
    validate_prepared_planar_member_sheet_network_binding,
)
from .prepared_member_sheet_network import (
    PreparedMemberSheetJointNetwork, query_prepared_member_sheet_joint_network,
    validate_prepared_member_sheet_joint_network_binding,
)
from .prepared_mixed_sheet_network import (
    PreparedMixedSheetJointNetwork, query_prepared_mixed_sheet_joint_network,
    validate_prepared_mixed_sheet_joint_network_binding,
    require_prepared_mixed_sheet_authored_material_coverage,
    require_prepared_mixed_sheet_reference_parameter_mapping,
)
from .authored_child_coverage import validate_prepared_authored_face_child_triangles
from .authored_partition_coverage import validate_prepared_authored_face_partition
from .edge_subcurve_preimages import (
    PolynomialEdgeDefinition, PolynomialEdgeAncestor, EdgeSubcurvePreimage,
    PreparedEdgeSubcurvePreimages, query_prepared_edge_subcurve_preimages,
    validate_prepared_edge_subcurve_preimages_binding,
)
from .material_regions import (
    MaterialSurfaceRegion, MaterialSurfaceRegions, query_material_surface_regions,
    validate_material_surface_regions_binding, evaluate_material_surface_region,
)
from .chart_fingerprints import chart_definition_fingerprint
from .material_cell_coverage import (
    validate_material_surface_region_triangles,
    validate_material_surface_region_triangles_xyz,
)
from .authored_boundary_correspondence import (
    AuthoredBoundaryCorrespondence, query_prepared_authored_boundary_correspondence,
    validate_prepared_authored_boundary_correspondence_binding,
)
from .authored_domain_coverage import validate_prepared_authored_face_triangles
from .authored_boundary_stations import (
    AuthoredBoundaryStations, query_prepared_authored_boundary_stations,
    validate_prepared_authored_boundary_station_coordinates,
)
from .authored_surface_evaluation import evaluate_prepared_authored_face
from .authored_curve_stations import (
    AuthoredCurveStations, query_prepared_authored_curve_stations,
    validate_prepared_authored_curve_station_coordinates,
)
from .authored_internal_stations import (
    AuthoredInternalStations, query_prepared_authored_internal_stations,
    validate_prepared_authored_internal_station_coordinates,
)
from .authored_material_stations import (
    AuthoredMaterialStations, query_prepared_authored_material_stations,
    validate_prepared_authored_material_station_coordinates,
)
from .coordinates import (
    model_to_world_points, world_to_model_points,
    model_to_world_vectors, world_to_model_vectors,
)
from .cylinder_charts import (
    CylinderAtlasStatus, CylinderAtlasErrorCode, CylinderAtlasError,
    CylinderAtlasPolicy, CylinderAtlasCertificate, CylinderSectorChart,
    CylinderOccurrence, CylinderInterface, CylinderBoundaryCycle,
    CylinderAtlasResult, CylinderOccurrenceRequest, CylinderOccurrenceSample,
    CylinderOccurrenceEvaluation, query_cylinder_atlas,
    validate_cylinder_atlas_binding, evaluate_cylinder_occurrences,
)
from .closure import ModelClosure, extract_model_closure
from .closure import model_closure_to_dict, model_closure_from_dict
from .component_partition import (
    IndependentComponent, ComponentMergeReason, ComponentRefusal, ComponentPartition,
    plan_independent_components, validate_component_partition_binding,
)
from .trimmed_charts import (
    TrimmedSurfaceChartQueryResult, TrimmedSurfaceChartQueryResults,
    query_trimmed_surface_charts_by_face,
)
from .cylinder_patch import (
    CylinderPatchStatus, CylinderPatchErrorCode, CylinderPatchError,
    CylinderPatchPolicy, CylinderPatchCertificate, CylinderPatchOccurrence,
    CylinderPatchLoop, CylinderPatchResult, CylinderPatchOccurrenceRequest,
    CylinderPatchSample, CylinderPatchEvaluation, query_cylinder_patch,
    validate_cylinder_patch_binding, evaluate_cylinder_patch_occurrences,
)
from .cylinder_open_component import (
    CylinderOpenComponentErrorCode, CylinderOpenComponentError,
    CylinderOpenComponentResult, CylinderOpenComponentEvaluation,
    query_cylinder_open_component, validate_cylinder_open_component_binding,
    evaluate_cylinder_open_component_occurrences,
)
from .entities import Edge, EntityKind, EntityRef, Face, OrientedEdge, Vertex, VertexRole
from .editing import (
    InsertResult,
    Measurement,
    PatternResult,
    circular_pattern,
    copy_entities,
    copy_rotated,
    copy_translated,
    insert_model,
    linear_pattern,
    measure,
    mirror_entities,
    move_entities,
    pattern_entities,
    rectangular_pattern,
    reverse_edge,
    reverse_face,
    rotate_entities,
    translate_entities,
)
from .errors import GeometryError, GeometryTopologyError
from .evaluation import (
    edge_tangent_many,
    evaluate_edge_many,
    evaluate_face_many,
    face_derivatives_many,
    face_normal_many,
    project_to_face_many,
)
from .features import (
    FeatureExecution,
    FeatureExecutor,
    FeatureHistory,
    FeatureInputRef,
    FeatureOutputRef,
    FeatureRecord,
    FeatureRegistry,
    FeatureResult,
    FeatureStatus,
    FeatureTopologyRole,
    RegenerationReport,
    builtin_feature_registry,
    feature_entity_owners,
)
from .intersections import (
    ExpectedImprintChange,
    FaceIntersection,
    ImprintApplication,
    ImprintOperation,
    ImprintPlan,
    apply_imprint,
    clip_line_to_face,
    intersect_faces,
    intersect_surfaces,
    line_cylinder,
    line_line,
    line_plane,
    numerical_surface_intersection,
    plane_cylinder,
    plane_plane,
    plan_imprint,
    query_intersection,
)
from .model import GeometryModel
from .trim_domains import (
    TrimBoundaryContact, TrimDomainError, TrimDomainErrorCode, TrimDomainResult,
    TrimInteriorRelation, query_trim_domain_relation, validate_trim_domain_binding,
)
from .identity import EntityHandle, Resolution, ResolutionStatus
from .transactions import AABBChange, ChangeSet, TopologyTransaction
from .tolerance import DEFAULT_TOLERANCE_POLICY, TolerancePolicy, feature_extent
from .transforms import AffineTransform
from .predicates import (
    CertifiedCurveTrace,
    DEFAULT_INTERSECTION_QUALIFICATION_POLICY,
    IntersectionCertificate,
    IntersectionComponent,
    IntersectionDimension,
    IntersectionKind,
    IntersectionQualificationPolicy,
    IntersectionQuality,
    IntersectionResult,
    ParameterLoop,
    ParameterRange as IntersectionParameterRange,
    ParameterRegion,
    qualified_line_line,
    qualified_line_cylinder,
    qualified_line_plane,
    qualified_plane_plane,
    qualified_segment_segment,
)
from .policies import MutationPolicy
from .spatial import (
    AABB,
    AABBTree,
    IndexDiagnostics,
    IndexUpdate,
    IndexUpdateKind,
    NearestQueryResult,
)
from .audit import (
    AuditEvidenceQuality,
    AuditEntity,
    AuditCode,
    AuditIssue,
    AuditMetrics,
    AuditPolicy,
    AuditReport,
    AuditScope,
    AuditSeverity,
    AuditWitness,
    BroadPhaseDiagnostics,
)
from .strict_audit import audit_changed_region, strict_audit
from .structural import (
    Attachment,
    AttachmentEvidence,
    AttachmentKind,
    AttachmentTargetKind,
    BoundaryPolicy,
    Coedge,
    ConnectivityPolicy,
    ConnectionIntent,
    FaceUse,
    FrozenMetadata,
    Junction,
    JunctionKind,
    JunctionMemberUse,
    Member,
    MemberEdgeUse,
    NonManifoldPolicy,
    Orientation,
    ParameterRange,
    Part,
    Sheet,
    SheetTopologyPolicy,
)
from .overlaps import (
    FaceOverlap,
    OverlapFragmentation,
    OverlapFragmentationPlan,
    OverlapOwnershipPolicy,
    OverlapQualificationError,
    plan_coplanar_fragmentation,
    apply_coplanar_fragmentation,
    find_coplanar_overlaps,
    fragment_coplanar_overlaps,
)
from .operations import (
    closest_point,
    fragment_face,
    project,
    punch_hole,
    split_face,
    split_face_at,
    split_face_between,
    strip_face,
    surface_point,
    transform,
    trim_face,
)
from .serialization import from_dict, read_geometry, to_dict, write_geometry
from .sketch import (
    SketchConstraint,
    SketchDefinition,
    SketchPlane,
    face_sketch_plane,
    materialize_sketch,
    solve_sketch,
)
from .extrusions import BezierDirectrix, EllipseDirectrix
from .surfaces import (
    CoonsSurface,
    Cone,
    Cylinder,
    ExtrudedSurface,
    Plane,
    RuledSurface,
    Surface,
    SurfaceProtocol,
    closest_uv,
    surface_normal,
)

__all__ = [
    "model_to_world_points",
    "world_to_model_points",
    "model_to_world_vectors",
    "world_to_model_vectors",
    "CylinderPatchStatus", "CylinderPatchErrorCode", "CylinderPatchError",
    "CylinderPatchPolicy", "CylinderPatchCertificate", "CylinderPatchOccurrence",
    "CylinderPatchLoop", "CylinderPatchResult", "CylinderPatchOccurrenceRequest",
    "CylinderPatchSample", "CylinderPatchEvaluation", "query_cylinder_patch",
    "validate_cylinder_patch_binding", "evaluate_cylinder_patch_occurrences",
    "CylinderAtlasStatus", "CylinderAtlasErrorCode", "CylinderAtlasError",
    "CylinderAtlasPolicy", "CylinderAtlasCertificate", "CylinderSectorChart",
    "CylinderOccurrence", "CylinderInterface", "CylinderBoundaryCycle",
    "CylinderAtlasResult", "CylinderOccurrenceRequest", "CylinderOccurrenceSample",
    "CylinderOccurrenceEvaluation", "query_cylinder_atlas",
    "validate_cylinder_atlas_binding", "evaluate_cylinder_occurrences",
    "TrimBoundaryContact", "TrimDomainError", "TrimDomainErrorCode",
    "TrimDomainResult", "TrimInteriorRelation", "query_trim_domain_relation",
    "validate_trim_domain_binding",
    "AABB",
    "AABBChange",
    "AABBTree",
    "AffineTransform",
    "Arc",
    "EllipticArc",
    "IntersectionBatchPolicy",
    "IntersectionPlan",
    "IntersectionApplication",
    "plan_intersections",
    "apply_intersections",
    "has_current_intersection_preparation",
    "PreparedFacePreimages",
    "PreparedModelScope",
    "PreparedVertexPreimages",
    "query_prepared_vertex_preimages",
    "validate_prepared_vertex_preimages_binding",
    "PreparedSheetJointComponent",
    "PreparedMemberSheetJointComponent",
    "query_prepared_member_sheet_joint_component",
    "validate_prepared_member_sheet_joint_component_binding",
    "PreparedMemberSheetJointNetwork",
    "query_prepared_member_sheet_joint_network",
    "PreparedPlanarMemberSheetNetwork",
    "query_prepared_planar_member_sheet_network",
    "validate_prepared_planar_member_sheet_network_binding",
    "validate_prepared_member_sheet_joint_network_binding",
    "PreparedMixedSheetJointNetwork",
    "query_prepared_mixed_sheet_joint_network",
    "validate_prepared_mixed_sheet_joint_network_binding",
    "require_prepared_mixed_sheet_authored_material_coverage",
    "require_prepared_mixed_sheet_reference_parameter_mapping",
    "query_prepared_sheet_joint_component",
    "validate_prepared_sheet_joint_component_binding",
    "validate_prepared_sheet_joint_component_selection",
    "validate_prepared_authored_face_child_triangles",
    "validate_prepared_authored_face_partition",
    "query_prepared_model_scope",
    "validate_prepared_model_scope_binding",
    "PreparedAuthoredConstraintScope",
    "query_prepared_authored_constraint_scope",
    "validate_prepared_authored_constraint_scope_binding",
    "AuthoredFaceDefinition",
    "query_prepared_face_preimages",
    "query_prepared_authored_face_definition",
    "validate_prepared_face_preimages_binding",
    "PolynomialEdgeDefinition",
    "PolynomialEdgeAncestor",
    "EdgeSubcurvePreimage",
    "PreparedEdgeSubcurvePreimages",
    "query_prepared_edge_subcurve_preimages",
    "validate_prepared_edge_subcurve_preimages_binding",
    "clone_prepared_geometry",
    "set_prepared_face_corners",
    "TrimmedSurfaceChart",
    "TrimmedSurfaceCharts",
    "query_trimmed_surface_charts",
    "validate_trimmed_surface_charts_binding",
    "evaluate_trimmed_surface_chart",
    "MaterialSurfaceRegion",
    "MaterialSurfaceRegions",
    "query_material_surface_regions",
    "validate_material_surface_regions_binding",
    "chart_definition_fingerprint",
    "validate_material_surface_region_triangles",
    "validate_material_surface_region_triangles_xyz",
    "AuthoredBoundaryCorrespondence",
    "query_prepared_authored_boundary_correspondence",
    "validate_prepared_authored_boundary_correspondence_binding",
    "validate_prepared_authored_face_triangles",
    "AuthoredBoundaryStations",
    "query_prepared_authored_boundary_stations",
    "validate_prepared_authored_boundary_station_coordinates",
    "evaluate_prepared_authored_face",
    "AuthoredCurveStations",
    "AuthoredInternalStations",
    "query_prepared_authored_internal_stations",
    "validate_prepared_authored_internal_station_coordinates",
    "AuthoredMaterialStations",
    "query_prepared_authored_material_stations",
    "validate_prepared_authored_material_station_coordinates",
    "query_prepared_authored_curve_stations",
    "validate_prepared_authored_curve_station_coordinates",
    "evaluate_material_surface_region",
    "JointEdge",
    "query_joint_edge",
    "CylinderIntersectionCurve",
    "QuadricIntersectionCurve",
    "BezierQuadricCurve",
    "ArcFrame",
    "Attachment",
    "AttachmentEvidence",
    "AttachmentKind",
    "AttachmentTargetKind",
    "AuditCode",
    "AuditEntity",
    "AuditEvidenceQuality",
    "AuditIssue",
    "AuditMetrics",
    "AuditPolicy",
    "AuditReport",
    "AuditScope",
    "AuditSeverity",
    "AuditWitness",
    "BoundaryPolicy",
    "BroadPhaseDiagnostics",
    "ChangeSet",
    "CertifiedCurveTrace",
    "Coedge",
    "ConnectivityPolicy",
    "ConnectionIntent",
    "CoonsSurface",
    "Cone",
    "CurveShape",
    "Cylinder",
    "DegenerateArcError",
    "DEFAULT_INTERSECTION_QUALIFICATION_POLICY",
    "Edge",
    "EntityKind",
    "EntityHandle",
    "EntityRef",
    "ExpectedImprintChange",
    "Face",
    "FaceIntersection",
    "FaceOverlap",
    "FaceUse",
    "FeatureExecution",
    "FeatureExecutor",
    "FeatureHistory",
    "FeatureInputRef",
    "FeatureOutputRef",
    "FeatureRecord",
    "FeatureRegistry",
    "FeatureResult",
    "FeatureStatus",
    "FeatureTopologyRole",
    "GeometryError",
    "GeometryModel",
    "GeometryTopologyError",
    "FrozenMetadata",
    "IndexDiagnostics",
    "IndexUpdate",
    "IndexUpdateKind",
    "ImprintApplication",
    "ImprintOperation",
    "ImprintPlan",
    "IntersectionComponent",
    "IntersectionCertificate",
    "IntersectionDimension",
    "IntersectionKind",
    "IntersectionQualificationPolicy",
    "IntersectionParameterRange",
    "IntersectionQuality",
    "IntersectionResult",
    "ParameterLoop",
    "InsertResult",
    "Measurement",
    "Member",
    "MemberEdgeUse",
    "ModelClosure",
    "MutationPolicy",
    "NearestQueryResult",
    "NonManifoldPolicy",
    "Orientation",
    "OrientedEdge",
    "OverlapFragmentation",
    "OverlapFragmentationPlan",
    "OverlapOwnershipPolicy",
    "OverlapQualificationError",
    "plan_coplanar_fragmentation",
    "apply_coplanar_fragmentation",
    "Plane",
    "PatternResult",
    "ParameterRange",
    "ParameterRegion",
    "Part",
    "RegenerationReport",
    "Resolution",
    "ResolutionStatus",
    "RuledSurface",
    "ExtrudedSurface",
    "BezierDirectrix",
    "EllipseDirectrix",
    "SketchConstraint",
    "SketchDefinition",
    "SketchPlane",
    "Sheet",
    "SheetTopologyPolicy",
    "Spline",
    "Straight",
    "Surface",
    "SurfaceProtocol",
    "TolerancePolicy",
    "TopologyTransaction",
    "Vertex",
    "VertexRole",
    "apply_imprint",
    "audit_changed_region",
    "closest_point",
    "clip_line_to_face",
    "closest_uv",
    "copy_entities",
    "copy_rotated",
    "copy_translated",
    "circular_pattern",
    "edge_tangent_many",
    "evaluate_edge_many",
    "evaluate_face_many",
    "extract_model_closure",
    "model_closure_to_dict",
    "model_closure_from_dict",
    "IndependentComponent",
    "ComponentMergeReason",
    "ComponentRefusal",
    "ComponentPartition",
    "plan_independent_components",
    "validate_component_partition_binding",
    "TrimmedSurfaceChartQueryResult",
    "TrimmedSurfaceChartQueryResults",
    "query_trimmed_surface_charts_by_face",
    "face_derivatives_many",
    "face_normal_many",
    "fragment_face",
    "fragment_coplanar_overlaps",
    "feature_entity_owners",
    "face_sketch_plane",
    "from_dict",
    "find_coplanar_overlaps",
    "feature_extent",
    "intersect_faces",
    "intersect_surfaces",
    "insert_model",
    "line_cylinder",
    "line_line",
    "line_plane",
    "qualified_line_line",
    "qualified_line_cylinder",
    "qualified_line_plane",
    "qualified_plane_plane",
    "qualified_segment_segment",
    "linear_pattern",
    "measure",
    "materialize_sketch",
    "mirror_entities",
    "move_entities",
    "numerical_surface_intersection",
    "pattern_entities",
    "plane_cylinder",
    "plane_plane",
    "plan_imprint",
    "query_intersection",
    "project",
    "project_to_face_many",
    "punch_hole",
    "read_geometry",
    "rectangular_pattern",
    "reverse_edge",
    "reverse_face",
    "rotate_entities",
    "split_face",
    "split_face_at",
    "split_face_between",
    "strip_face",
    "strict_audit",
    "solve_sketch",
    "surface_normal",
    "surface_point",
    "to_dict",
    "transform",
    "translate_entities",
    "trim_face",
    "write_geometry",
    "builtin_feature_registry",
    "DEFAULT_TOLERANCE_POLICY",
    "Junction",
    "JunctionKind",
    "JunctionMemberUse",
]

__version__ = "0.4.5"
