"""Lightweight structural-surface geometry shared by the ANY ecosystem."""

from .curves import Arc, ArcFrame, CurveShape, DegenerateArcError, Spline, Straight
from .entities import Edge, EntityKind, EntityRef, Face, OrientedEdge, Vertex
from .editing import (
    InsertResult,
    Measurement,
    PatternResult,
    circular_pattern,
    copy_entities,
    insert_model,
    linear_pattern,
    measure,
    mirror_entities,
    reverse_edge,
    reverse_face,
)
from .errors import GeometryError, GeometryTopologyError
from .features import (
    FeatureExecution,
    FeatureExecutor,
    FeatureHistory,
    FeatureInputRef,
    FeatureOutputRef,
    FeatureRecord,
    FeatureRegistry,
    FeatureResult,
    FeatureStatus,
    RegenerationReport,
    builtin_feature_registry,
)
from .intersections import (
    FaceIntersection,
    intersect_faces,
    intersect_surfaces,
    line_cylinder,
    line_line,
    line_plane,
    numerical_surface_intersection,
    plane_cylinder,
    plane_plane,
)
from .model import GeometryModel
from .overlaps import (
    FaceOverlap,
    OverlapFragmentation,
    find_coplanar_overlaps,
    fragment_coplanar_overlaps,
)
from .operations import (
    closest_point,
    fragment_face,
    project,
    punch_hole,
    split_face,
    split_face_at,
    split_face_between,
    strip_face,
    surface_point,
    transform,
    trim_face,
)
from .serialization import from_dict, read_geometry, to_dict, write_geometry
from .sketch import (
    SketchConstraint,
    SketchDefinition,
    SketchPlane,
    face_sketch_plane,
    materialize_sketch,
    solve_sketch,
)
from .surfaces import (
    CoonsSurface,
    Cone,
    Cylinder,
    Plane,
    RuledSurface,
    Surface,
    SurfaceProtocol,
    closest_uv,
    surface_normal,
)

__all__ = [
    "Arc",
    "ArcFrame",
    "CoonsSurface",
    "Cone",
    "CurveShape",
    "Cylinder",
    "DegenerateArcError",
    "Edge",
    "EntityKind",
    "EntityRef",
    "Face",
    "FaceIntersection",
    "FaceOverlap",
    "FeatureExecution",
    "FeatureExecutor",
    "FeatureHistory",
    "FeatureInputRef",
    "FeatureOutputRef",
    "FeatureRecord",
    "FeatureRegistry",
    "FeatureResult",
    "FeatureStatus",
    "GeometryError",
    "GeometryModel",
    "GeometryTopologyError",
    "InsertResult",
    "Measurement",
    "OrientedEdge",
    "OverlapFragmentation",
    "Plane",
    "PatternResult",
    "RegenerationReport",
    "RuledSurface",
    "SketchConstraint",
    "SketchDefinition",
    "SketchPlane",
    "Spline",
    "Straight",
    "Surface",
    "SurfaceProtocol",
    "Vertex",
    "closest_point",
    "closest_uv",
    "copy_entities",
    "circular_pattern",
    "fragment_face",
    "fragment_coplanar_overlaps",
    "face_sketch_plane",
    "from_dict",
    "find_coplanar_overlaps",
    "intersect_faces",
    "intersect_surfaces",
    "insert_model",
    "line_cylinder",
    "line_line",
    "line_plane",
    "linear_pattern",
    "measure",
    "materialize_sketch",
    "mirror_entities",
    "numerical_surface_intersection",
    "plane_cylinder",
    "plane_plane",
    "project",
    "punch_hole",
    "read_geometry",
    "reverse_edge",
    "reverse_face",
    "split_face",
    "split_face_at",
    "split_face_between",
    "strip_face",
    "solve_sketch",
    "surface_normal",
    "surface_point",
    "to_dict",
    "transform",
    "trim_face",
    "write_geometry",
    "builtin_feature_registry",
]

__version__ = "0.1.0"
