"""Whole-document planar interior/boundary stiffener network owner receipt.

This is the additive planar interior-stiffener owner slice. It generalizes the
boundary-only member Sheet network without weakening it: the whole connected
Plane/literal-Straight document, arbitrary finite straight continuous Member
chains with unique source carriers both on the component boundary and in the
interior of original face material, exact edge-local point Attachments, and the
member-on-Sheet joints generated by the owner intersection application are all
accounted for and certified. It grants no beam discretization, load transfer,
solver, external-reference or publication authority.

Certification chain, in order:
1. Every source/current Sheet/Part/Member/use/Attachment/Junction of the one
   connected document is accounted for; unsupported kinds refuse.
2. Original Member material membership: each original carrier segment is
   proved, with exact rational arithmetic and a complete boundary-event
   decomposition (no sampled acceptance oracle), to lie inside the union of
   the closed original face materials, holes excluded.
3. Source ancestry: current carriers are exact restrictions of the original
   straight carriers under unchanged certified tolerances.
4. Exact affine endpoint residual bounds certify Member stations, point
   stations and generated joint stations; squared-norm convexity extends the
   two endpoint residuals to each whole claimed interval.
5. Generated member-on-Sheet joints: each member_on_face_boundary Attachment
   and its overlap Junction are re-derived against the live owner incidence
   contracts, and their target edge is proved to lie in the closed material of
   the authored root of every current face carrying it. A multi-Sheet overlap
   Junction must declare exactly the live sheets_using_edge inventory.
6. Generated member point contacts: each member_through_face Attachment is
   re-derived through the qualified original->current Member mapping and the
   immutable authored root material proof; its target face UV, source and
   current point stations must agree within the unchanged recorded owner
   tolerance, and its crossing/endpoint/multi_way Junction must declare
   exactly the complete participating Member and Sheet owner sets.

Generated records, IDs and provenance alone never establish source membership:
the geometry is re-derived from the immutable source/live snapshots every
time. Reserved boundaries (refused, not guessed): point-range member
attachments, member_on_sheet_intersection and member-on-face-interior
attachments, original Junctions, orientation references, curved Members and
non-planar supports. Original material certificates use only owned authored
Sheet faces, so orphan faces cannot connect a disconnected Member.
"""
from dataclasses import dataclass, fields
from fractions import Fraction
import json
from uuid import UUID

from .definition_binding import definition_checksum
from .edge_subcurve_preimages import (
    PreparedEdgeSubcurvePreimages,
    EdgeSubcurvePreimage, PolynomialEdgeAncestor, PolynomialEdgeDefinition,
    query_prepared_edge_subcurve_preimages,
    validate_prepared_edge_subcurve_preimages_binding,
)
from .errors import GeometryError
from .material_cell_coverage import _frame
from .prepared_model_scope import validate_prepared_model_scope_binding
from .prepared_model_scope import PreparedModelScope
from .prepared_face_preimages import PreparedFacePreimages, AuthoredFaceDefinition
from .prepared_member_sheet_network import (
    _qualify_member_chain, _qualify_point_attachments,
    _point, _distance_squared, _carrier_tolerance,
)
from .prepared_sheet_joint_component import PreparedSheetJointComponent, _query_component
from .serialization import _decode_surface, _QUADRIC_VERSION
from .surfaces import Plane


def _encode(value):
    return json.dumps(value, sort_keys=True, separators=(',', ':'), allow_nan=False)


def _require(condition, detail):
    if not condition:
        raise GeometryError('prepared planar member Sheet network ' + detail)


def _cross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])


def _dot(a, b):
    return sum(x*y for x, y in zip(a, b))


def _orient(a, b, c):
    return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])


def _on_segment(p, a, b):
    """Exact: p lies on the closed two-dimensional segment [a, b]."""
    if _orient(a, b, p) != 0:
        return False
    return (min(a[0], b[0]) <= p[0] <= max(a[0], b[0]) and
            min(a[1], b[1]) <= p[1] <= max(a[1], b[1]))


def _inside_polygon(p, loop):
    """Exact crossing parity of one simple loop; p must not be on its boundary."""
    inside = False
    for a, b in loop:
        if (a[1] > p[1]) != (b[1] > p[1]):
            crossing = a[0]+(p[1]-a[1])*(b[0]-a[0])/(b[1]-a[1])
            if p[0] < crossing:
                inside = not inside
    return inside


def _point_in_face(p, loops):
    """Closed outer material minus open hole interiors; exact rationals."""
    if any(_on_segment(p, a, b) for a, b in loops[0]):
        return True
    if not _inside_polygon(p, loops[0]):
        return False
    for hole in loops[1:]:
        if any(_on_segment(p, a, b) for a, b in hole):
            continue
        if _inside_polygon(p, hole):
            return False
    return True


def _segments_meet(a, b, c, d):
    """Exact: two closed segments share at least one point."""
    ab = (_orient(a, b, c), _orient(a, b, d))
    cd = (_orient(c, d, a), _orient(c, d, b))
    return (ab[0]*ab[1] < 0 and cd[0]*cd[1] < 0 or
            _on_segment(c, a, b) or _on_segment(d, a, b) or
            _on_segment(a, c, d) or _on_segment(b, c, d))


def _qualified_loops(loops, check):
    """Refuse degenerate, open, backtracking or nonsimple original loops."""
    for loop in loops:
        check()
        _require(len(loop) >= 3, 'has a degenerate original boundary loop')
        _require(all(a != b for a, b in loop), 'has a degenerate original boundary edge')
        _require(all(first[1] == second[0]
                     for first, second in zip(loop, (*loop[1:], loop[0]))),
                 'has an open original boundary loop')
        count = len(loop)
        for index in range(count):
            a, b = loop[index]
            following = loop[(index+1) % count][1]
            _require(_orient(a, b, following) != 0 or
                     sum((y-x)*(z-y) for x, y, z in zip(a, b, following)) > 0,
                     'has a backtracking original boundary loop')
            for other in range(index+2, count):
                check()
                if other == count-1 and index == 0:
                    continue
                _require(not _segments_meet(a, b, *loop[other]),
                         'has a nonsimple original boundary loop')


def _on_plane(frame, point):
    offset = tuple(value-origin for value, origin in zip(point, frame['origin']))
    return _dot(offset, _cross(frame['u'], frame['v'])) == 0


def _chart_uv(frame, point):
    offset = tuple(value-origin for value, origin in zip(point, frame['origin']))
    return tuple(_dot(offset, row) for row in frame['inverse'])


def _planar_face_charts(source, check, edge_tolerance=None):
    """Exact planar UV charts and literal straight loops of owned Sheet faces.

    Only faces carried by an authored Sheet FaceUse are material owners; a
    sheet-less orphan face can never certify Member material membership.
    """
    owned = set()
    for sheet in source['sheets'].values():
        for key in sheet['face_use_ids']:
            _require(key in source['face_uses'],
                     'has a Sheet FaceUse that is unavailable')
            owned.add(source['face_uses'][key]['face_id'])
    _require(all(face_id in source['faces'] for face_id in owned),
             'has a Sheet FaceUse without an owned authored face')
    charts = {}
    for face_id in sorted(owned):
        check()
        face = source['faces'][face_id]
        _require(face.get('parameterization') is None,
                 'does not qualify original parameterizations')
        support = _decode_surface(face['surface'], strict=True, schema_version=_QUADRIC_VERSION)
        _require(type(support) is Plane, 'requires original Plane faces')
        frame = _frame(support)
        uv_loops, xyz_loops = [], []
        for loop in (face['loop'], *face['holes']):
            uv_loop, xyz_loop = [], []
            for edge_id, forward in loop:
                check()
                edge = source['edges'][edge_id]
                _require(edge['curve'] == {'type': 'straight'},
                         'requires literal Straight original boundaries')
                start = tuple(Fraction(float(x))
                              for x in source['vertices'][edge['start']]['position'])
                end = tuple(Fraction(float(x))
                            for x in source['vertices'][edge['end']]['position'])
                if edge_tolerance is None:
                    _require(_on_plane(frame, start) and _on_plane(frame, end),
                             'has an original boundary vertex off the support plane')
                else:
                    tolerance = edge_tolerance(edge_id)
                    for point in (start,end):
                        uv = _chart_uv(frame,point)
                        projection = tuple(o+uv[0]*u+uv[1]*v for o,u,v in
                                           zip(frame['origin'],frame['u'],frame['v']))
                        _require(_distance_squared(point,projection) <= tolerance**2,
                                 'current child trim leaves its bound support tolerance')
                if not forward:
                    start, end = end, start
                uv_loop.append((_chart_uv(frame, start), _chart_uv(frame, end)))
                xyz_loop.append((start, end))
            uv_loops.append(tuple(uv_loop))
            xyz_loops.append(tuple(xyz_loop))
        _qualified_loops(uv_loops, check)
        charts[face_id] = (frame, tuple(uv_loops), tuple(xyz_loops))
    return charts


def _boundary_events(a, b, loops):
    """Exact segment parameters where [a, b] meets any loop edge."""
    events = set()
    direction = (b[0]-a[0], b[1]-a[1])
    _require(direction != (0,0), 'has a degenerate projected segment')
    for loop in loops:
        for c, d in loop:
            edge = (d[0]-c[0], d[1]-c[1])
            denominator = direction[0]*edge[1]-direction[1]*edge[0]
            if denominator:
                offset = (c[0]-a[0], c[1]-a[1])
                station = (offset[0]*edge[1]-offset[1]*edge[0])/denominator
                other = (offset[0]*direction[1]-offset[1]*direction[0])/denominator
                if 0 <= station <= 1 and 0 <= other <= 1:
                    events.add(station)
            elif _orient(a, b, c) == 0 and _orient(a, b, d) == 0:
                # Collinear overlap: the whole closed contact is boundary.
                length = _dot(direction, direction)
                first = _dot((c[0]-a[0], c[1]-a[1]), direction)/length
                second = _dot((d[0]-a[0], d[1]-a[1]), direction)/length
                low, high = (first, second) if first <= second else (second, first)
                low, high = max(low, Fraction(0)), min(high, Fraction(1))
                if low <= high:
                    events.add(low)
                    events.add(high)
    return events


def _segment_in_face_uv(a, b, loops):
    """Exact: the whole segment lies in the closed face material."""
    if not _point_in_face(a, loops) or not _point_in_face(b, loops):
        return False
    ordered = sorted({Fraction(0), Fraction(1)} | _boundary_events(a, b, loops))
    for low, high in zip(ordered, ordered[1:]):
        middle = (low+high)/2
        if not _point_in_face(((1-middle)*a[0]+middle*b[0],
                               (1-middle)*a[1]+middle*b[1]), loops):
            return False
    return True


def _on_boundary_xyz(point, xyz_loops):
    """Exact: a three-dimensional point lies on one loop edge."""
    for loop in xyz_loops:
        for a, b in loop:
            offset = tuple(p-q for p, q in zip(point, a))
            direction = tuple(p-q for p, q in zip(b, a))
            if not any(_cross(direction, offset)) and 0 <= _dot(offset, direction) <= _dot(direction, direction):
                return True
    return False


def _material_membership(controls, charts, check):
    """Certify one straight carrier segment against the union of materials.

    The complete exact boundary-event decomposition makes every open interval
    between consecutive events homogeneous with respect to every coplanar
    face, so one exact rational midpoint classification per interval decides
    coverage without any sampled acceptance oracle.
    """
    segment = tuple(tuple(Fraction(*value) for value in point) for point in controls)
    coplanar = [(face_id, frame, _chart_uv(frame, segment[0]),
                 _chart_uv(frame, segment[1]), uv_loops)
                for face_id, (frame, uv_loops, _) in sorted(charts.items())
                if _on_plane(frame, segment[0]) and _on_plane(frame, segment[1])]
    _require(coplanar, 'original Member carrier lies in no original support plane')
    events = {Fraction(0), Fraction(1)}
    for face_id, frame, a, b, uv_loops in coplanar:
        check()
        events |= _boundary_events(a, b, uv_loops)
    ordered = sorted(events)
    intervals = []
    for low, high in zip(ordered, ordered[1:]):
        check()
        middle = (low+high)/2
        faces = sorted(face_id for face_id, frame, a, b, uv_loops in coplanar
                       if _point_in_face(((1-middle)*a[0]+middle*b[0],
                                          (1-middle)*a[1]+middle*b[1]), uv_loops))
        _require(faces, 'original Member carrier leaves the original face material')
        intervals.append({'interval': [[low.numerator, low.denominator],
                                       [high.numerator, high.denominator]],
                          'material_faces': faces})
    endpoints = []
    for point in segment:
        faces = sorted(face_id for face_id, frame, a, b, uv_loops in coplanar
                       if _point_in_face(_chart_uv(frame, point), uv_loops))
        if not faces:
            faces = sorted(face_id for face_id, (_, _, xyz_loops) in charts.items()
                           if _on_boundary_xyz(point, xyz_loops))
        _require(faces, 'original Member carrier endpoint leaves the original face material')
        endpoints.append(faces)
    return {'endpoint_material_faces': endpoints,
            'interior_material_intervals': intervals}


def _current_edge_controls(current, edge):
    row = current['edges'][edge]
    _require(row['curve'] == {'type': 'straight'},
             'requires a literal Straight current carrier')
    controls = []
    for vertex in (row['start'], row['end']):
        _require(vertex in current['vertices'], 'current carrier vertex is unavailable')
        controls.append(tuple(Fraction(float(x))
                              for x in current['vertices'][vertex]['position']))
    _require(controls[0] != controls[1], 'requires a nondegenerate current carrier')
    return tuple(controls)


@dataclass(frozen=True, slots=True)
class PreparedPlanarMemberSheetNetwork(PreparedSheetJointComponent):
    """Every planar member, point and generated joint relation of one document.

    Complete source/current records remain in ``scope``. The additional JSON
    accounts for all bounded relations, material memberships and generated
    member-on-Sheet joints separately from the Sheet-joint records. It grants
    no beam discretization, load transfer, solver, external-reference or
    publication authority.
    """
    relations_json: str = ''
    edge_preimages: object = None
    bounded_relation_mapping_qualified: bool = True
    beam_discretization_qualified: bool = False
    load_transfer_qualified: bool = False
    external_reference_transfer_qualified: bool = False
    solver_qualified: bool = False

    @property
    def relations(self):
        return json.loads(self.relations_json)


@dataclass(frozen=True)
class _PlanarRelations:
    members: tuple
    attachment_ids: tuple
    current_attachment_ids: tuple
    member_junction_ids: tuple
    point_attachment_ids: tuple
    point_junction_ids: tuple
    material_face_roots: tuple
    source_edges: tuple
    current_edges: tuple
    material_roots: tuple
    certified_current_edges: tuple
    source_vertices: tuple
    source_index: object
    payload: str
    edge_preimages: object

    def output_signature(self, result):
        return _receipt_signature(result)

    def part_ids(self, data):
        # Whole-document inventory includes even unchanged empty Parts. This
        # records their definitions without qualifying external semantics.
        return set(data['parts'])

    def qualify_junction(self, data, row):
        """Re-verify one already certified generated member/point Junction."""
        if row['kind'] == 'overlap':
            _require(row['id'] in self.member_junction_ids and
                     row['connection_intent'] == 'connect' and
                     len(row['member_uses']) == 1 and
                     len(row['attachment_ids']) == 1 and
                     row['attachment_ids'][0] in self.current_attachment_ids,
                     'has unsupported generated member Junction semantics')
            return tuple(row['sheet_ids']), set(row['attachment_ids'])
        _require(row['kind'] in ('crossing', 'endpoint', 'multi_way') and
                 row['id'] in self.point_junction_ids and
                 row['connection_intent'] == 'connect' and
                 len(row['member_uses']) >= 1 and
                 all(key in self.point_attachment_ids
                     for key in row['attachment_ids']),
                 'has unsupported generated point Junction semantics')
        return tuple(row['sheet_ids']), set(row['attachment_ids'])

    def complete_records(self, encoded, data):
        records = json.loads(encoded)
        # The engine calls this once per document after the component expansion
        # reached its fixpoint, so the captured records are the full selection.
        _require({row['id'] for row in records['sheets']} == set(data['sheets']),
                 'requires the whole document as one connected component')
        _require({row['id'] for row in records['faces']} == set(data['faces']),
                 'requires every document face in the selected Sheet component records')
        boundary = {row['id'] for row in records['edges']}
        if data is self.source_index:
            # Every material root used by a membership certificate is an owned
            # authored face of the selected component; orphan faces cannot
            # connect a disconnected Member through a material certificate.
            _require(set(self.material_face_roots) <=
                     {row['face_id'] for row in records['face_uses']},
                     'has a material root outside the selected component')
            carriers, certified = self.source_edges, set(self.material_roots)
        else:
            carriers, certified = self.current_edges, set(self.certified_current_edges)
        # Interior carriers need not lie on the component boundary; every
        # carrier is either recorded there or material-certified per root.
        _require(set(carriers) <= boundary | certified,
                 'member carrier is outside the selected component boundary and material')
        # Interior carrier edges and their endpoint vertices belong to the
        # source/current component inventories even off the boundary.
        interior = sorted(set(carriers) - boundary)
        edges_by_id = {row['id']: row for row in records['edges']}
        edges_by_id.update({key: data['edges'][key] for key in interior})
        records['edges'] = [edges_by_id[key] for key in sorted(edges_by_id)]
        vertex_keys = set(self.source_vertices)
        for key in interior:
            vertex_keys.update((data['edges'][key]['start'], data['edges'][key]['end']))
        records['members'] = [data['members'][key] for key in self.members]
        use_keys = sorted({key for member in self.members
                           for key in data['members'][member]['edge_use_ids']})
        records['member_edge_uses'] = [data['member_edge_uses'][key] for key in use_keys]
        for kind, keys in (('vertices', vertex_keys),
                           ('parts', set(data['parts']))):
            by_id = {row['id']: row for row in records[kind]}
            by_id.update({key: data[kind][key] for key in keys})
            records[kind] = [by_id[key] for key in sorted(by_id)]
        return _encode(records)

    def validate_dependencies(self, data, deps, *, original):
        # Member carriers are checked against the completed component boundary
        # or their material certificates in complete_records; here every
        # document Member/Part must be ours.
        _require(set(data['members']) == set(self.members), 'has unaccounted Members')
        for part in data['parts'].values():
            _require(set(part['member_ids']) <= set(self.members),
                     'has unaccounted Part Members')

    def validate_final(self, model, scope, *, cancellation_check):
        validate_prepared_edge_subcurve_preimages_binding(
            model, self.edge_preimages, cancellation_check=cancellation_check)
        validate_prepared_model_scope_binding(model, scope)

    def current_plane_geometry(self, model, data, faces, check):
        records = {row.edge_id: row for row in self.edge_preimages.records}
        def tolerance(edge):
            if edge in records:
                return _carrier_tolerance(model,records[edge])
            controls = _current_edge_controls(data,edge)
            length = float(sum((b-a)**2 for a,b in zip(*controls)))**0.5
            return Fraction(model.tolerance.effective_length(length))
        _planar_face_charts(data,check,tolerance)
        return {key: _decode_surface(data['faces'][key]['surface'],strict=True,
                                    schema_version=_QUADRIC_VERSION) for key in faces}


def _qualify_member_joints(model, scope, source, current, member_relations,
                           record_by_edge, charts, descendants, member_attachments,
                           check):
    """Certify every generated member-on-Sheet joint against live contracts."""
    roots_by_edge, uses_by_owner = {}, {}
    for relation in member_relations:
        for mapping in relation['source_use_mappings']:
            for edge in mapping['current_carriers']:
                roots_by_edge[edge] = mapping['source_carrier']
        for use in relation['current_member_uses']:
            uses_by_owner[(use['member_id'], use['edge_id'])] = use
    junctions_by_attachment = {}
    for key, row in current['junctions'].items():
        if row['kind'] == 'overlap':
            for attachment in row['attachment_ids']:
                junctions_by_attachment.setdefault(attachment, []).append(key)
    joint_relations, member_junction_ids = [], []
    expected = {(member,edge) for member,edge in uses_by_owner
                if model.faces_using_edge(edge)}
    declared = [(current['attachments'][key]['member_id'],
                 current['attachments'][key]['target_id']) for key in member_attachments]
    _require(len(declared) == len(set(declared)) and set(declared) == expected,
             'generated member overlap inventory is incomplete')
    for attachment_id in member_attachments:
        check()
        row = current['attachments'][attachment_id]
        member = row['member_id']
        _require(row['kind'] == 'member_on_face_boundary' and
                 row['target_kind'] == 'edge' and row['source_kind'] == 'member' and
                 member in current['members'] and row['source_id'] == member and
                 row['connection_intent'] == 'connect' and row['evidence'] == 'exact' and
                 row['max_residual'] <= row['tolerance_used'] and
                 isinstance(row['target_parameters'],(list,tuple)) and
                 len(row['target_parameters']) == 1 and row['sheet_id'] is None and
                 row['part_id'] in (None, current['members'][member]['part_id']),
                 'has unsupported generated member Attachment semantics')
        edge = row['target_id']
        use = uses_by_owner.get((member, edge))
        _require(use is not None,
                 'generated member Attachment target is not a current carrier')
        _require(isinstance(row['member_range'],(list,tuple)) and len(row['member_range'])==2 and
                 isinstance(row['target_parameters'][0],(list,tuple)) and
                 len(row['target_parameters'][0])==2,
                 'has malformed generated overlap ranges')
        p, q = (Fraction(float(value)) for value in row['member_range'])
        _require(p < q, 'has unsupported point-range member Attachment semantics')
        c, d = (Fraction(float(value)) for value in row['target_parameters'][0])
        _require(0 <= c < d <= 1, 'has an unsupported member Attachment target interval')
        u, v = (Fraction(float(value)) for value in use['parent_range'])
        _require(p == u and q == v and c == 0 and d == 1,
                 'generated member Attachment must cover its full carrier use and target edge')
        reverse = use['orientation'] == 'reversed'
        def local(station):
            value = (station-u)/(v-u)
            return 1-value if reverse else value
        controls = _current_edge_controls(current, edge)
        tolerance = min(Fraction(float(row['tolerance_used'])),
                        _carrier_tolerance(model, record_by_edge[edge]))
        # The member/edge station error is affine; its squared norm is convex,
        # so the worse exact endpoint residual bounds the WHOLE claimed
        # interval under the unchanged owner tolerance.
        pairings = (((_point(controls, local(p)), _point(controls, c)),
                     (_point(controls, local(q)), _point(controls, d))),
                    ((_point(controls, local(p)), _point(controls, d)),
                     (_point(controls, local(q)), _point(controls, c))))
        bound = min(max(_distance_squared(first, second) for first, second in pairing)
                    for pairing in pairings)
        _require(bound <= tolerance**2,
                 'generated member Attachment exceeds its unchanged owner tolerance')
        junction_ids = junctions_by_attachment.get(attachment_id, [])
        _require(len(junction_ids) == 1,
                 'generated member Attachment lacks a unique Junction')
        junction = current['junctions'][junction_ids[0]]
        # Guard every declared length BEFORE indexing the member use row.
        _require(junction['kind'] == 'overlap' and
                 junction['connection_intent'] == 'connect' and
                 len(junction['member_uses']) == 1 and
                 junction['attachment_ids'] == [attachment_id],
                 'has unsupported generated member Junction semantics')
        use_row = junction['member_uses'][0]
        _require(isinstance(use_row['member_range'],(list,tuple)) and
                 len(use_row['member_range'])==2,
                 'has malformed generated overlap Junction range')
        _require(use_row['member_id'] == member and
                 Fraction(float(use_row['member_range'][0])) == p and
                 Fraction(float(use_row['member_range'][1])) == q and
                 len(junction['sheet_ids']) >= 1,
                 'has unsupported generated member Junction semantics')
        faces = sorted(face_id for face_id, face in current['faces'].items()
                       for loop in (face['loop'], *face['holes'])
                       for edge_id, _ in loop if edge_id == edge)
        literal_sheets = sorted({use_row['sheet_id']
                                 for use_row in current['face_uses'].values()
                                 if use_row['face_id'] in set(faces)})
        # A multi-Sheet overlap Junction must equal the complete live
        # sheets_using_edge inventory; every owner root is certified below.
        _require(literal_sheets == sorted(model.sheets_using_edge(edge)) and
                 sorted(junction['sheet_ids']) == literal_sheets,
                 'generated member Junction Sheet incidence changed')
        for face_id in faces:
            check()
            root = descendants.get(face_id)
            _require(root is not None and root in charts,
                     'generated member Joint face has no authored planar root')
            frame, uv_loops, _ = charts[root]
            segment = _current_edge_controls(current, edge)
            uv_segment = tuple(_chart_uv(frame,point) for point in segment)
            projections = tuple(tuple(o+uv[0]*u+uv[1]*v for o,u,v in
                                      zip(frame['origin'],frame['u'],frame['v']))
                                for uv in uv_segment)
            _require(all(_distance_squared(point,projection) <= tolerance**2
                         for point,projection in zip(segment,projections)) and
                     _segment_in_face_uv(*uv_segment, uv_loops),
                     'generated member Joint target leaves its original face material')
        joint_relations.append({
            'joint_role': 'member_on_face_boundary',
            'member': member, 'source_carrier': roots_by_edge.get(edge),
            'attachment': row, 'junction': junction,
            'sheets': sorted(junction['sheet_ids']), 'boundary_faces': faces,
            'member_range': [[p.numerator, p.denominator], [q.numerator, q.denominator]],
            'target_interval': [[c.numerator, c.denominator], [d.numerator, d.denominator]],
            'carrier_orientation': use['orientation'],
            'member_joint_squared_distance_bound': [bound.numerator, bound.denominator],
            'coordinate_tolerance': [tolerance.numerator, tolerance.denominator]})
        member_junction_ids.append(junction_ids[0])
    return joint_relations, member_junction_ids


def _qualify_member_point_contacts(model, scope, source, current, member_relations,
                                   record_by_edge, charts, descendants, carriers,
                                   point_attachments, check):
    """Certify every generated member point contact against live contracts.

    Each member_through_face Attachment is re-derived through the qualified
    original->current Member mapping and the immutable authored root material
    proof: the declared target UV, the source carrier point and the current
    carrier point must agree within the unchanged recorded owner tolerance.
    Each crossing/endpoint/multi_way Junction must declare exactly the
    complete participating Member and Sheet owner sets of its Attachments.
    """
    relations_by_member = {relation['source_member']['id']: relation
                           for relation in member_relations}
    def current_tolerance(edge):
        record = record_by_edge.get(edge)
        if record is not None:
            return _carrier_tolerance(model,record)
        controls = _current_edge_controls(current,edge)
        length = float(sum((b-a)**2 for a,b in zip(*controls)))**0.5
        return Fraction(model.tolerance.effective_length(length))
    current_charts = _planar_face_charts(current, check, current_tolerance)
    actual_inventory, expected_inventory, contact_vertices = set(), set(), {}
    # Contact completeness comes from authored carriers intersecting owned
    # authored materials, independently of the supplied Attachment/Junction graph.
    for member, relation in relations_by_member.items():
        for mapping in relation['source_use_mappings']:
            controls = tuple(tuple(Fraction(*x) for x in point)
                             for point in carriers[mapping['source_carrier']][2])
            delta = tuple(b-a for a,b in zip(*controls))
            for root, (frame, loops, _) in charts.items():
                check()
                normal = _cross(frame['u'], frame['v'])
                denominator = _dot(delta, normal)
                if denominator == 0:
                    continue
                station = _dot(tuple(o-a for o,a in zip(frame['origin'], controls[0])),
                               normal)/denominator
                if not 0 <= station <= 1:
                    continue
                point = _point(controls, station)
                if not _point_in_face(_chart_uv(frame, point), loops):
                    continue
                candidates = set()
                for use in relation['current_member_uses']:
                    if use['edge_id'] not in mapping['current_carriers']:
                        continue
                    record = record_by_edge[use['edge_id']]
                    tolerance = _carrier_tolerance(model, record)
                    vertices = (current['edges'][use['edge_id']]['start'],
                                current['edges'][use['edge_id']]['end'])
                    stations = tuple(Fraction(float(x)) for x in use['parent_range'])
                    if use['orientation']=='reversed':
                        stations = stations[::-1]
                    for vertex, global_station in zip(vertices, stations):
                        xyz = tuple(Fraction(float(x)) for x in
                                    current['vertices'][vertex]['position'])
                        if _distance_squared(xyz, point) <= tolerance**2:
                            candidates.add((vertex,global_station))
                _require(len(candidates) == 1,
                         'authored member contact lacks one canonical current contact vertex')
                vertex,global_station = next(iter(candidates))
                for use in source['face_uses'].values():
                    if use['face_id'] == root:
                        expected_inventory.add((member, use['sheet_id'], vertex,global_station))
    # The owner producer unions transverse contact Sheet owners and Member
    # station occurrences at each canonical vertex, then declares their full
    # Cartesian contact set. A second Member can thereby supply a Sheet that
    # is coplanar with the first Member. Reproduce that physical event closure
    # from the independently derived contacts, never declared Attachments.
    contact_groups = {}
    for member,sheet,vertex,station in expected_inventory:
        owners,participants = contact_groups.setdefault(vertex,(set(),set()))
        owners.add(sheet)
        participants.add((member,station))
    expected_inventory = {(member,sheet,vertex,station)
                          for vertex,(owners,participants) in contact_groups.items()
                          for member,station in participants for sheet in owners}
    point_junctions = {key: row for key, row in current['junctions'].items()
                       if row['kind'] in ('crossing', 'endpoint', 'multi_way')}
    junctions_by_attachment = {}
    for key, row in point_junctions.items():
        for attachment in row['attachment_ids']:
            junctions_by_attachment.setdefault(attachment, []).append(key)
    contact_relations = []
    for attachment_id in point_attachments:
        check()
        row = current['attachments'][attachment_id]
        member = row['member_id']
        _require(row['kind'] == 'member_through_face' and
                 row['target_kind'] == 'face' and row['source_kind'] == 'member' and
                 member in current['members'] and row['source_id'] == member and
                 row['connection_intent'] == 'connect' and row['evidence'] == 'exact' and
                 not row['lineage'] and row['sheet_id'] is not None and
                 row['part_id'] in (None, current['members'][member]['part_id']) and
                 row['max_residual'] <= row['tolerance_used'],
                 'has unsupported generated member point Attachment semantics')
        _require(isinstance(row['member_range'],(list,tuple)) and len(row['member_range'])==2,
                 'has malformed generated point range')
        p, q = (Fraction(float(value)) for value in row['member_range'])
        _require(p == q and 0 <= p <= 1,
                 'has unsupported generated member point Attachment stations')
        _require(isinstance(row['target_parameters'],(list,tuple)) and
                 len(row['target_parameters']) == 2 and
                 all(isinstance(pair,(list,tuple)) and len(pair) == 2 and pair[0] == pair[1]
                     for pair in row['target_parameters']),
                 'has unsupported generated member point Attachment UV')
        u, w = (Fraction(float(pair[0])) for pair in row['target_parameters'])
        face = row['target_id']
        _require(face in current['faces'],
                 'generated member point Attachment target face is unavailable')
        root = descendants.get(face)
        _require(root is not None and root in charts,
                 'generated member point Attachment face has no authored planar root')
        source_frame, uv_loops, _ = charts[root]
        frame, child_loops, _ = current_charts[face]
        sheet = row['sheet_id']
        _require(sheet in current['sheets'] and
                 sheet in {use['sheet_id'] for use in current['face_uses'].values()
                           if use['face_id'] == face},
                 'generated member point Attachment Sheet does not own its target face')
        relation = relations_by_member.get(member)
        _require(relation is not None,
                 'generated member point Attachment member is unqualified')
        use = next((use for use in relation['current_member_uses']
                    if Fraction(float(use['parent_range'][0])) <= p <=
                    Fraction(float(use['parent_range'][1]))), None)
        _require(use is not None,
                 'generated member point Attachment station leaves its current carrier')
        low, high = (Fraction(float(value)) for value in use['parent_range'])
        _require(low < high, 'generated member point Attachment carrier use is degenerate')
        local = (p-low)/(high-low)
        if use['orientation'] == 'reversed':
            local = 1-local
        _require(0 <= local <= 1,
                 'generated member point Attachment station leaves its current carrier')
        edge = use['edge_id']
        record = record_by_edge.get(edge)
        _require(record is not None,
                 'generated member point Attachment has no retained carrier ancestry')
        current_point = _point(_current_edge_controls(current, edge), local)
        mapping = next((mapping for mapping in relation['source_use_mappings']
                        if Fraction(*mapping['source_span'][0]) <= p <=
                        Fraction(*mapping['source_span'][1])), None)
        _require(mapping is not None,
                 'generated member point Attachment station leaves its original use span')
        a, b = (Fraction(*value) for value in mapping['source_span'])
        native = (p-a)/(b-a)
        if mapping['orientation'] == 'reversed':
            native = 1-native
        source_carrier = mapping['source_carrier']
        _require(source_carrier in carriers,
                 'generated member point Attachment carrier is unqualified')
        original_controls = tuple(tuple(Fraction(*value) for value in point)
                                  for point in carriers[source_carrier][2])
        source_point = _point(original_controls, native)
        tolerance = min(Fraction(float(row['tolerance_used'])),
                        _carrier_tolerance(model, record))
        station_bound = _distance_squared(source_point, current_point)
        uv_point = tuple(origin + u*axis_u + w*axis_v for origin, axis_u, axis_v
                         in zip(frame['origin'], frame['u'], frame['v']))
        uv_bound = _distance_squared(uv_point, current_point)
        source_uv_bound = _distance_squared(source_point, uv_point)
        _require(station_bound <= tolerance**2 and uv_bound <= tolerance**2,
                 'generated member point Attachment exceeds its unchanged owner tolerance')
        _require(source_uv_bound <= tolerance**2,
                 'generated member point Attachment source-to-UV bound exceeds its unchanged owner tolerance')
        def projected(chart, point):
            uv = _chart_uv(chart, point)
            xyz = tuple(o + uv[0]*a + uv[1]*b for o,a,b in
                        zip(chart['origin'], chart['u'], chart['v']))
            _require(_distance_squared(xyz, point) <= tolerance**2,
                     'generated member point Attachment leaves its target support plane')
            return uv
        _require(_point_in_face(projected(source_frame, source_point), uv_loops),
                 'generated member point Attachment leaves its original face material')
        _require(_point_in_face((u,w), child_loops) and
                 _point_in_face(projected(frame, current_point), child_loops),
                 'generated member point Attachment leaves its named current child trim')
        candidates = {vertex for item in relation['current_member_uses']
                      for vertex in (current['edges'][item['edge_id']]['start'],
                                     current['edges'][item['edge_id']]['end'])
                      if _distance_squared(tuple(Fraction(float(x)) for x in
                           current['vertices'][vertex]['position']), current_point) <= tolerance**2}
        _require(len(candidates) == 1,
                 'generated member point Attachment lacks one canonical current contact vertex')
        vertex = next(iter(candidates))
        incident = {v for loop in (current['faces'][face]['loop'],*current['faces'][face]['holes'])
                    for edge_id,_ in loop for v in
                    (current['edges'][edge_id]['start'],current['edges'][edge_id]['end'])}
        _require(vertex in incident,
                 'generated member point Attachment vertex is not incident to its named child trim')
        actual_inventory.add((member, sheet, vertex,p))
        contact_vertices[attachment_id] = vertex
        junction_ids = junctions_by_attachment.get(attachment_id, [])
        _require(len(junction_ids) == 1,
                 'generated member point Attachment lacks a unique Junction')
        contact_relations.append({
            'joint_role': 'member_through_face',
            'member': member, 'source_carrier': source_carrier,
            'current_carrier': edge, 'attachment': row,
            'face': face, 'material_root': root, 'sheet': sheet,
            'junction': current['junctions'][junction_ids[0]],
            'member_station': [p.numerator, p.denominator],
            'target_uv': [[u.numerator, u.denominator], [w.numerator, w.denominator]],
            'point_station_squared_distance_bound':
                [station_bound.numerator, station_bound.denominator],
            'point_target_squared_distance_bound':
                [uv_bound.numerator, uv_bound.denominator],
            'point_source_target_squared_distance_bound':
                [source_uv_bound.numerator, source_uv_bound.denominator],
            'coordinate_tolerance': [tolerance.numerator, tolerance.denominator]})
    point_junction_ids = []
    _require(actual_inventory == expected_inventory and
             len(actual_inventory) == len(point_attachments),
             'generated member point contact inventory is incomplete')
    for key in sorted(point_junctions):
        check()
        junction = point_junctions[key]
        attachments = junction['attachment_ids']
        _require(attachments and all(attachment in set(point_attachments)
                                      for attachment in attachments),
                 'generated point Junction lacks its member point Attachments')
        vertices = {contact_vertices[attachment] for attachment in attachments}
        _require(len(vertices) == 1,
                 'generated point Junction combines spatially separate contacts')
        vertex = next(iter(vertices))
        _require(set(attachments) == {key for key,value in contact_vertices.items()
                                      if value == vertex},
                 'generated point Junction omits a canonical contact participant')
        expected_uses = sorted({(current['attachments'][attachment]['member_id'],
                                 tuple(Fraction(float(value))
                                       for value in
                                       current['attachments'][attachment]['member_range']))
                                for attachment in attachments})
        _require(all(isinstance(use['member_range'],(list,tuple)) and
                     len(use['member_range'])==2 for use in junction['member_uses']),
                 'has malformed generated point Junction range')
        declared_uses = sorted((use['member_id'],
                                tuple(Fraction(float(value))
                                      for value in use['member_range']))
                               for use in junction['member_uses'])
        _require(declared_uses == expected_uses,
                 'generated point Junction Member uses are incomplete')
        expected_sheets = sorted({current['attachments'][attachment]['sheet_id']
                                   for attachment in attachments})
        _require(sorted(junction['sheet_ids']) == expected_sheets,
                 'generated point Junction Sheet owners are incomplete')
        stations = {pair for _, pair in expected_uses}
        kind = ('multi_way' if len(expected_uses)+len(expected_sheets) > 2 else
                'endpoint' if all(station[0] in (Fraction(0), Fraction(1))
                                  for station in stations) else 'crossing')
        _require(junction['kind'] == kind and
                 junction['connection_intent'] == 'connect',
                 'has unsupported generated point Junction semantics')
        point_junction_ids.append(key)
    return contact_relations, point_junction_ids


def _qualify(model, scope, source, current, cancellation_check):
    """Prove the whole planar document; boundary and interior Members alike."""
    for document in (source,current):
        owned = set()
        for sheet in document['sheets'].values():
            for key in sheet['face_use_ids']:
                _require(key in document['face_uses'], 'has an unavailable Sheet FaceUse')
                owned.add(document['face_uses'][key]['face_id'])
        _require(owned == set(document['faces']),
                 'requires every document face to have a selected Sheet owner; unowned faces refuse')
    _require(not source['junctions'], 'does not remap pre-existing Junctions')
    _require(set(source['sheets']) == set(current['sheets']),
             'Sheet set changed between documents')
    members = sorted(source['members'])
    _require(members, 'needs at least one source Member')
    _require(set(current['members']) == set(members), 'lost or gained Members')
    _require(source['parts'] == current['parts'], 'Part fields or membership changed')
    ancestry = query_prepared_edge_subcurve_preimages(
        model, expected_revision=scope.face_preimages.revision,
        cancellation_check=cancellation_check)
    ancestry_by_root = {}
    for row in ancestry.records:
        ancestry_by_root.setdefault(row.ancestor.definition.edge_id, []).append(row)
    record_by_edge = {row.edge_id: row for row in ancestry.records}
    parents = {}
    for row in scope.current_document.get('replacement_history', ()):
        if row['old'][0] == 'edge':
            for kind, child in row['new']:
                _require(kind == 'edge', 'unsupported edge replacement kind')
                parents.setdefault(child, []).append(row['old'][1])
    lineage_cache = {}
    def check():
        if cancellation_check is not None and cancellation_check(
                'prepared planar member Sheet network'):
            raise GeometryError('prepared planar member Sheet network cancelled')
    carriers = {}
    charts = _planar_face_charts(source, check)
    descendants = {child: root for root, children in scope.face_preimages.face_descendants
                   for child in children}
    member_relations = []
    source_edges, current_edges, old_use_ids, current_use_ids = [], [], [], []
    certified_current_edges, material_roots = [], set()
    material_face_roots = set()
    for member in members:
        check()
        relation = _qualify_member_chain(model, scope, source, current, member,
            ancestry_by_root, record_by_edge, carriers, check, _require)
        old_use_ids.extend(relation['source_member']['edge_use_ids'])
        current_use_ids.extend(relation['current_member']['edge_use_ids'])
        source_edges.extend(relation['source_carriers'])
        current_edges.extend(use['edge_id'] for use in relation['current_member_uses'])
        certified_current_edges.extend(relation['current_carriers'])
        memberships = []
        for root in relation['source_carriers']:
            check()
            records, intervals, original_controls = carriers[root]
            membership = _material_membership(original_controls, charts, check)
            material_face_roots.update(face
                for faces in membership['endpoint_material_faces'] for face in faces)
            material_face_roots.update(face
                for interval in membership['interior_material_intervals']
                for face in interval['material_faces'])
            memberships.append(membership)
            material_roots.add(root)
        relation['member_role'] = 'straight_planar_chain'
        relation['material_memberships'] = memberships
        member_relations.append(relation)
    _require(len(old_use_ids) == len(set(old_use_ids)) and
             set(old_use_ids) == set(source['member_edge_uses']),
             'has unaccounted original MemberEdgeUses')
    _require(len(current_use_ids) == len(set(current_use_ids)) and
             set(current_use_ids) == set(current['member_edge_uses']),
             'has unaccounted current MemberEdgeUses')
    points, point_vertices, attachment_relations = _qualify_point_attachments(
        model, scope, source, current, carriers, parents, lineage_cache, check, _require)
    member_attachments = sorted(key for key, row in current['attachments'].items()
                                if row['kind'] == 'member_on_face_boundary')
    joint_relations, member_junction_ids = _qualify_member_joints(
        model, scope, source, current, member_relations, record_by_edge,
        charts, descendants, member_attachments, check)
    point_attachments = sorted(key for key,row in current['attachments'].items()
                               if row['kind'] == 'member_through_face')
    contact_relations, point_junction_ids = _qualify_member_point_contacts(
        model, scope, source, current, member_relations, record_by_edge,
        charts, descendants, carriers, point_attachments, check)
    for key, row in current['attachments'].items():
        check()
        if row['kind'] == 'vertex_on_edge':
            _require(key in points, 'has unaccounted current point Attachments')
        elif row['kind'] == 'member_on_face_boundary':
            _require(key in member_attachments, 'has unaccounted generated member Attachments')
        elif row['kind'] == 'member_through_face':
            _require(key in point_attachments, 'has unaccounted generated point Attachments')
        else:
            _require(row['kind'] == 'sheet_on_joint', 'has unaccounted current Attachments')
    for key, row in current['junctions'].items():
        check()
        if row['kind'] == 'sheet_joint':
            _require(not row['member_uses'], 'has unsupported Junction/member semantics')
        elif row['kind'] == 'overlap':
            _require(key in member_junction_ids,
                     'has unaccounted generated member Junctions')
        elif row['kind'] in ('crossing', 'endpoint', 'multi_way'):
            _require(key in point_junction_ids, 'has unaccounted generated point Junctions')
        else:
            _require(False, 'has unsupported current Junction semantics')
    _require(all(not (set(row['attachment_ids']) & set(points))
                 for row in current['junctions'].values()),
             'has unsupported Junction/member semantics')
    payload = _encode({'members': member_relations, 'attachments': attachment_relations,
                       'member_joints': joint_relations, 'point_contacts': contact_relations})
    result = _PlanarRelations(members=tuple(members), attachment_ids=tuple(points),
        current_attachment_ids=tuple(member_attachments+point_attachments),
        member_junction_ids=tuple(member_junction_ids), point_attachment_ids=tuple(point_attachments),
        point_junction_ids=tuple(point_junction_ids), material_face_roots=tuple(sorted(material_face_roots)),
        source_edges=tuple(source_edges), current_edges=tuple(current_edges),
        material_roots=tuple(sorted(material_roots)),
        certified_current_edges=tuple(sorted(set(certified_current_edges))),
        source_vertices=tuple(point_vertices), source_index=source, payload=payload, edge_preimages=ancestry)
    result.validate_final(model, scope, cancellation_check=cancellation_check)
    return result


def query_prepared_planar_member_sheet_network(model, current_joint_edge_id, *,
        expected_revision=None, cancellation_check=None):
    """Qualify every planar relation of the whole connected document."""
    holder = []

    def qualify(*args):
        relation = _qualify(*args)
        holder.append(relation)
        return relation

    def receipt(*args, **kwargs):
        relation = holder[0]
        return PreparedPlanarMemberSheetNetwork(*args, **kwargs,
            relations_json=relation.payload, edge_preimages=relation.edge_preimages)

    return _query_component(model, current_joint_edge_id,
        expected_revision=expected_revision, cancellation_check=cancellation_check,
        relation_factory=qualify, result_factory=receipt)


def _receipt_signature(receipt):
    """Pin supplied content without model serialization or copying hooks."""
    _require(type(receipt) is PreparedPlanarMemberSheetNetwork,
             'needs its distinct owner receipt')
    _require(all(type(getattr(receipt, name)) is str for name in
                 ('relations_json', 'source_records_json', 'current_records_json')) and
             type(receipt.edge_preimages) is PreparedEdgeSubcurvePreimages,
             'needs plain immutable relation and ancestry fields')
    # Definition fingerprints alone are not a type certificate: a Mapping can
    # imitate the encoded shape of a dataclass and execute code while traversed.
    # Reject every non-plain graph node BEFORE computing the signature.
    allowed = (PreparedPlanarMemberSheetNetwork, PreparedModelScope,
               PreparedFacePreimages, AuthoredFaceDefinition,
               PreparedEdgeSubcurvePreimages, EdgeSubcurvePreimage,
               PolynomialEdgeAncestor, PolynomialEdgeDefinition)
    active = set()
    def plain(value):
        kind = type(value)
        if any(kind is scalar for scalar in (type(None), bool, int, float, str)):
            return
        if kind is UUID:
            _require(type(object.__getattribute__(value, 'int')) is int,
                     'needs a plain immutable UUID')
            return
        _require(kind is tuple or any(kind is cls for cls in allowed),
                 'needs plain immutable owner fields')
        identifier = id(value)
        _require(identifier not in active, 'has cyclic receipt fields')
        active.add(identifier)
        try:
            if kind is tuple:
                for item in value:
                    plain(item)
            else:
                for field in fields(kind):
                    plain(object.__getattribute__(value, field.name))
        finally:
            active.remove(identifier)
    try:
        plain(receipt)
    except RecursionError as error:
        raise GeometryError(
            'prepared planar member Sheet network invalid receipt nesting') from error
    try:
        return definition_checksum(receipt)
    except RecursionError as error:
        raise GeometryError(
            'prepared planar member Sheet network invalid receipt nesting') from error
    except (TypeError, ValueError) as error:
        raise GeometryError(
            'prepared planar member Sheet network invalid receipt definition') from error


def validate_prepared_planar_member_sheet_network_binding(model, receipt, *,
        cancellation_check=None):
    """Rederive all planar relations; omissions cannot qualify."""
    # Even callback-free source serialization can execute user copy hooks.
    # Pin evidence before owner/model work, and inspect it after the LAST guard.
    signature = _receipt_signature(receipt)
    validate_prepared_model_scope_binding(model, receipt.scope)
    expected = query_prepared_planar_member_sheet_network(model, receipt.joint_edge_id,
        expected_revision=receipt.scope.face_preimages.revision,
        cancellation_check=cancellation_check)
    _require(_receipt_signature(expected) == signature and
             _receipt_signature(receipt) == signature, 'definition binding changed')
    validate_prepared_model_scope_binding(model, receipt.scope)
    _require(_receipt_signature(receipt) == signature, 'definition binding changed')
